### ISSUE TITLE
Closing the source code before saving

### ISSUE THREAD

**Issue by Brand3000** [mostafaznv/nova-ckeditor#113]
It'd be great to close (process) the source editor before sending the variable on the create/update action on the form.

**Comment by mostafaznv** [comment]
Hi, could you explain your idea? Why do you want this behavior, and what is the main advantage of it?

**Comment by Brand3000** [comment]
If I edit smth and forgot to close the source editor, my changes are not processed properly and lost =(
We need to catch somehow sort of beforesave event in vue and close the source editor programmatically.

**Comment by mostafaznv** [comment]
I got it.
thanks for the report. I will take a look at it soon.

**Comment by mostafaznv** [comment]
Apologies for the delay.
Your requested feature has been added to the package. please update to the [7.1.0](https://github.com/mostafaznv/nova-ckeditor/releases/tag/7.1.0)

**Comment by Brand3000** [comment]
That's fine! Thanks a lot! 
But I have an issue upon updating. To be exact, look at the two conficts:
mostafaznv/larupload[1.0.0, ..., 1.0.5] require intervention/image ^2.7 -> satisfiable by intervention/image[2.7.0, 2.7.1, 2.7.2].
mostafaznv/larupload 2.0.0 requires intervention/image ^3.1.0 -> satisfiable by intervention/image[3.1.0, ..., 3.4.0].

Actually, I don't understand where this second line come from and I'd rather stick to the 1 version. Could you help me fixing this issue, please?

**Comment by mostafaznv** [comment]
It's due to the latest version of `larupload`. Starting from version 2.0.0, support for `intervation/image:^2.0.0` has been dropped. If you've directly added either `larupload` or `intervation/image` to your `composer.json`, I recommend removing both and relying on the dependencies provided by nova-ckeditor.

Please be aware that there are numerous breaking changes in `intervation/image` v3.
