### ISSUE TITLE
Plugins support [help?]

### ISSUE THREAD

**Issue by muhammadsaeedparacha** [mostafaznv/nova-ckeditor#15]
Is there a way to add Ck Editor plugins to it?

**Comment by mostafaznv** [comment]
Hi @muhammadsaeedparacha 

For now, it's not possible.
In CkEditor v5 we have to add plugins on build time. we can't use CDN version of any plugin (look at [this](https://ckeditor.com/docs/ckeditor5/latest/installation/getting-started/installing-plugins.html#adding-a-plugin-to-an-editor)). so I can't make a dynamic way to add extra plugins to my default build.

Another way is building custom CkEditor builds using Ckeditor [online tool](https://ckeditor.com/ckeditor-5/online-builder/) and  replace that build with the default one. but this is not a good idea because almost all of my custom plugins and features will be lost and it will cause some trouble.

Tell me what plugin do you need?
If it is a plugin that is suitable for everyone, I can add it to the package.

**Comment by muhammadsaeedparacha** [comment]
Well I intended to use it to maintain company documentation and contracts. Like a full fledged Google Docs. For that I am looking to add plugins for:

Pagination (Tell where natural page break would be)
Manual Page Breaks
Export to word / pdf
Live Collaboration.

Since these are paid plugins of ek editor, and the licence key needs to be available at build time. 
Maybe we can have a option of adding lisence key in a global var like `window.ckeditor-license-key` and consume it from there.

I'll also have a developer look into how much of an effort would it be to develop those.

**Comment by mostafaznv** [comment]
I can add Pagination, Manual Page Breaks and Export plugins but I don't know anything about Live Collaboration.
If you want to add paid plugins to the editor, you have to fork this project and make your changes in your own repository.
